#! /bin/bash

current_year=$(date +%Y)

package=$(grep AC_INIT ../configure.ac | cut -d[ -f2 | cut -d] -f1)
version=$(grep AC_INIT ../configure.ac | cut -d[ -f3 | cut -d] -f1)
bugs=$(grep AC_INIT ../configure.ac | cut -d[ -f4 | cut -d] -f1)

xgettext \
    --no-wrap \
    --add-comments=TRANSLATORS: \
    --output=- \
    --package-name="$package" \
    --package-version="$version" \
    --copyright-holder="Mister Guinness" \
    --msgid-bugs-address="$bugs" \
    ../src/extension.js ../src/prefs.js ../src/utilities.js | \
    sed -e 's/# SOME DESCRIPTIVE TITLE./# Language translation template file. Generated by redo_pot.sh, DO NOT EDIT./' \
        -e "s/# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR./# Mister Guinness <https:\/\/github.com\/MisterGuinness>, $current_year./" \
        -e "s/# Copyright (C) YEAR/# Copyright (C) $current_year/" \
        -e 's/Language: \\n/Language: en\\n/' \
        -e 's/; charset=CHARSET/; charset=UTF-8/' > new.pot
